chore: remove deprecated kube-rbac-proxy
validator-labs/validator-plugin-maas pull request #185
Opened 2024-12-05 04:39 UTC by arturshadnik

## Issue
Resolves #183 

## Description
`kube-rbac-proxy`, which was previously used to secure the metrics server is being deprecated.

This PR:
- removes all use of `kube-rbac-proxy` and switches to the new recommended method for securing the metrics server using the built-in `WithAuthenticationAndAuthorization` feature from `Controller-Runtime`
- updates manifests and helm charts
- small kustomize update `config/default/kustomization.yaml`. `patchesStrategicMerge` is deprecated -> `patches`

2024-12-05 20:20 UTC, mattwelke commented
Reviewed together offline.

* kube-rbac-proxy was doing auth for the metrics server.
* controller-runtime authors  make auth code available and kuebbuilder authors used it instead of the proxy.
* PR follows approach recommended by kubebuilder authors to add flags to main.go etc to control metrics, with metrics defaulting to enabled on port 8443 (helm chart default behavior).
* Found that the DevSpace config doesn't have the flag to start the metrics server, which means it defaults to being disabled (`main.go` default behavior), but that's fine because don't need metrics in DevSpace local dev.
* Found that the `Service` associated with reading metrics is always created, even when metrics are disabled (because we have no `if` in the Helm chart for it). We will update it to exclude the `Service` when running in DevSpace (via new `values.yaml` value).
* Manual testing was performed to test that metrics can be retrieved at that port. But we had to add a new ClusterRoleBinding to do it. We asked for clarification about it on https://github.com/kubernetes-sigs/kubebuilder/discussions/3907#discussioncomment-11477582.

2024-12-05 20:21 UTC, mattwelke requested changes
Reviewed together offline.

* kube-rbac-proxy was doing auth for the metrics server.
* controller-runtime authors make auth code available and kuebbuilder authors used it instead of the proxy.
* PR follows approach recommended by kubebuilder authors to add flags to main.go etc to control metrics, with metrics defaulting to enabled on port 8443 (helm chart default behavior).
* Found that the DevSpace config doesn't have the flag to start the metrics server, which means it defaults to being disabled (main.go default behavior), but that's fine because don't need metrics in DevSpace local dev.
* Found that the Service associated with reading metrics is always created, even when metrics are disabled (because we have no if in the Helm chart for it). We will update it to exclude the Service when running in DevSpace (via new values.yaml value).
* Manual testing was performed to test that metrics can be retrieved at that port. But we had to add a new ClusterRoleBinding to do it. We asked for clarification about it on https://github.com/kubernetes-sigs/kubebuilder/discussions/3907#discussioncomment-11477582.

2024-12-09 17:43 UTC, TylerGillson approved these changes

2024-12-09 17:44 UTC, TylerGillson commented
@arturshadnik great work. Please create an epic to mandate cert-manager for validator and all plugins.

2024-12-09 17:45 UTC, merged